service: my-express-application
plugins:
  - serverless-plugin-typescript
  - serverless-offline


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    offline_prefix: ${self:provider.stage}
    
    
custom:
  tableName: 'users-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
  serverless-offline:
    prefix: ${opt:stage, self:provider.stage}

functions:
#  app:
#    handler: server.handler
#    events:
#      - http: ANY /
#      - http: 'ANY /{proxy+}'

  hello:
    handler: lambda/lambda.hello
    events:
      - http: GET /
  getDev:
    handler: lambda/devHandler.getDev
    events:
      - http: GET /dev
  postDev:
    handler: lambda/devHandler.postDev
    events:
      - http: 'POST /dev/{id+}'
  info:
    handler: lambda/serverHandler.info
    events:
      - http: 'GET /server/info'
  error:
    handler: lambda/lambda.err
    events:
      - http: GET /test-error

